site_name: The Index
theme: 'material'

extra:
  palette:
    primary: 'light blue'
    accent: 'purple'

extra:
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)


